theme: jekyll-theme-slate
title: Smile
image: https://smilecord.github.io/files/logo.png
url: https://smilecord.github.io
description: Smile is a feature-rich Discord bot. It has epic commands which will make you 〝Smile!〞
