theme: jekyll-theme-cayman
title: VoxBot
image: https://VoxBot.github.io/files/logo.png
url: https://VoxBot.github.io
description: VoxBot is a feature-rich Discord bot. It has epic commands which will make you smile!
