theme: jekyll-theme-cayman
title: JazzRam
image: https://smilecord.github.io/files/logo.png
url: https://jazzram.github.io
description: Jazzram is a feature-rich Discord bot. It has epic commands which will make you Smile! BOOM! That is jazz baby!
