theme: jekyll-theme-cayman
title: VoxBot
image: https://VoxBot.github.io/files/logo.png
url: https://VoxBot.github.io
description: VoxBot is a feature-rich Discord bot. It has epic commands which will make you smile!
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
google_analytics_anonymize: false
darkmode: false
colors:
    gradient_left: "#FF0000"
    gradient_right: "#FFFFFF"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#FF0000" # this default to gradient_color
    section_title: "#FF0000" # this default to gradient_color
